### ISSUE TITLE
Since updating from Nuxt 2.15.4 to 2.15.8, auto import components no longer work

### ISSUE THREAD

**Issue by toddpadwick** [nuxt/components#230] opened 2021-09-02 15:32 UTC
Nuxt version 2.15.8

**Describe the bug**

All my components are saved to the root of the components directory - so no potential issue with missing prefixes there.
When I try and add a component into my pages, for example...
```
/components/CookieConsent.vue

/layouts/defaut.vue:
<template>
  <div class="app">
  	<main class="main">
		    <Nuxt />
		</main>
	<cookie-consent :decline-allowed="false" position="bottom-left"/>
  </div>
</template>

...i get the following error:

```
 Unknown custom element: <cookie-consent> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

**Comment by pi0** [comment] 2021-09-05 20:55
Hi @toddpadwick. I tried to reproduct issue based on details but seems working! Would you please try forking [this sandbox](https://codesandbox.io/s/optimistic-leakey-j4rcx?file=/layouts/default.vue:37-51) to see if somehow can reproduce issue?

Otherwise, it is probably a dependency issue, you might want to recreate `package-lock.json` or `yarn.lock`

**Comment by alhirzel** [comment] 2021-09-12 20:42
I'm seeing the same thing with a fresh install and fresh `yarn.lock`. Any thoughts? It installs `@nuxt/component` version 2.1.8.

Excerpt from `package.json':
```json
  "dependencies": {
    "bootstrap-vue": "^2.21.2",
    "nuxt": "^2.15.8"
  }
```

```text
yarn install v1.22.11
info No lockfile found.
[1/4] Resolving packages...
warning bootstrap-vue > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning nuxt > @nuxt/webpack > webpack-hot-middleware > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning nuxt > @nuxt/webpack > webpack > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning nuxt > @nuxt/webpack > postcss-preset-env > postcss-color-gray > postcss-values-parser > flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "bootstrap-vue > bootstrap@4.6.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning "bootstrap-vue > portal-vue@2.1.7" has unmet peer dependency "vue@^2.5.18".
warning "nuxt > @nuxt/components@2.2.1" has unmet peer dependency "consola@*".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 15.97s.
```

**Comment by oussj** [comment] 2021-11-12 23:32
same issue 
nuxt: 2.15.8
nuxt/component: 2.1.8

**Comment by toddpadwick** [comment] 2022-02-04 14:57
Hi @pi0  I have uploaded my boilerplate project to a sandbox. I couldn't re-create the issue with your sandbox so I just uploaded my own. As you say, could be a conflict with another module that's not on yours. if you check the console, you can see the unknown custom element errors https://codesandbox.io/s/charming-mahavira-25thq?file=/pages/index.vue
Hope that helps.

**Comment by danielroe** [comment] 2022-02-05 10:31
@toddpadwick In your nuxt.config you've specifically added a prefix:

```js
  components: [
    {
      path: '~/components',
      extensions: ['vue'],
      prefix: 'app',
      pathPrefix: false,
      ignore: ['~components/pages', '**/_**']
    }
  ],
```

So instead of accessing `<v-button>`, for example, you should access `<app-v-button>`. [**Working codesandbox**](https://codesandbox.io/s/stupefied-river-vzgn3?file=/pages/index.vue).

**Comment by toddpadwick** [comment] 2022-02-07 07:34
Hi @danielroe, sorry, that was a mistake I made a few days ago, when I copied something another user recommended me to try in [this issue](https://github.com/nuxt/nuxt.js/issues/8851), however, it still doesn't work even when I simply have `components:true` which it should right?. I've updated the sandbox here https://codesandbox.io/s/charming-mahavira-25thq?file=/nuxt.config.js

**Comment by toddpadwick** [comment] 2022-02-07 07:48
Hi @danielroe you are right, sorry thats a mistake but not actually one that I have locally. I just tried that in the sandbox as someone suggested I do so in [this thread](https://github.com/nuxt/nuxt.js/issues/8851).  Locally, I have `components:true`. The odd thing is in the sandbox, it works as you have linked. However, for me locally, I just can't replicate it: It just doesn't load the components – I don't understand. Could therefore, it be an environment issue? I am going to ask another dev to pull down my codebase and try on their machine to try.

**Comment by danielroe** [comment] 2022-02-07 07:58
@toddpadwick Check your components.md file in .nuxt to see how Nuxt is resolving the names. (The full path should be printed out when you start Nuxt.)

And check `npm why @nuxt/components`. You could also try explicitly upgrading it or adding it to your package dependencies.

**Comment by toddpadwick** [comment] 2022-02-11 15:44
Hi @danielroe  There is no components.md file in .nuxt - see screenshot:
<img width="271" alt="Screenshot 2022-02-11 at 16 41 22" src="https://user-images.githubusercontent.com/36191462/153621980-acb9e93c-b5a0-44ef-87d4-68dd12504251.png">

And when I try running `npm why @nuxt/components` I get the unknown command notice:
```
Todds-MacBook-Pro:usrem toddpadwick$ npm why @nuxt/components

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /Users/toddpadwick/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.8 /Users/toddpadwick/.nvm/versions/node/v13.11.0/lib/node_modules/npm
```

**Comment by danielroe** [comment] 2022-02-11 15:55
It is the `readme.md` file I'm referring to.

**Comment by toddpadwick** [comment] 2022-02-11 16:14
I've got it working 🎉. .

1. I removed node and NPM
2. Re-installed latest stable release (was on v13, now on v16)
2. deleted the entire repo
3. Re-installed packages
4. Ran npm audit fix

 and now it works. No idea why
 
 Thanks for your help. Shame I can't help anyone else figure it out any more specifically though, as it seems like whatever it is, is happening to lots of people.

**Comment by danielroe** [comment] 2022-02-11 17:27
Glad to hear it!

**Closed by danielroe** 2022-02-11 17:27 UTC

**Comment by devalexdom** [comment] 2022-06-27 17:43
@toddpadwick @danielroe 
The problem is that is taking the subfolder as a prefix... Any idea how to fix it?
I have now this issue with Nuxt 2.15.8 
![imagen](https://user-images.githubusercontent.com/41310150/176002286-c526b172-3171-4fb7-ba26-ad0d6ff7f6c5.png)

Thank you

**Comment by toddpadwick** [comment] 2022-06-28 11:28
I think that's the default behaviour with `components:true` – for me that is my preference. I'm not sure how to turn it off though.
