### ISSUE TITLE
Every component import creates its own JS file

### ISSUE THREAD

**Issue by Remcoman** [nuxt/components#155] opened 2021-02-22 15:22 UTC
**Describe the bug**

I thought it was just me doing weird stuff, but using the latest nuxt (2.15.1) it seems like every auto import creates its own JS file. It also seems to not look at 

It does not matter how small the component is.

So if `@nuxt/components` finds 100 components then you get 100 files.

**To Reproduce**
1. Create a new nuxt app (2.15.1) using the official instructions
2. Run 'npm run build -- --analyze'
3. See that logo is included as its own js file. Even though it is a tiny component.

**Expected behavior**
Logo should be part of the page js instead.

**Screenshots**

Nuxt 2.15.1
![Screenshot 2021-02-22 at 16 14 35](https://user-images.githubusercontent.com/564275/108728040-74e1dc00-7529-11eb-8a55-b0c5646d509d.png)

Nuxt 2.14
![Screenshot 2021-02-22 at 16 07 43](https://user-images.githubusercontent.com/564275/108728085-82976180-7529-11eb-96f3-c98673011228.png)

**Comment by Remcoman** [comment] 2021-02-22 15:49
Some additional information: it seems the components are loaded after the "main" js file was loaded. Components which are not referenced are not loaded, but their files still exist in the dist folder.

**Comment by pi0** [comment] 2021-02-22 17:17
Hi @Remcoman. This is part of hybrid loader strategy change. but i agree it is not a good DX specially when see them in build result it can be confusing.

> Logo should be part of the page js instead.

If you see bundle analyzer result and also checking devtools in production, no additional chunk is being loaded for logo. It will be only used when component is dynamically referenced in a way that loader could not auto import it.

**Comment by pi0** [comment] 2021-04-06 20:23
(closing since it is intended behavior and additional chunks don't add performance penalty and will bo be loaded dynamically on-demand)

**Closed by pi0** 2021-04-06 20:23 UTC
