### ISSUE TITLE
nuxt-components in IDEA

### ISSUE THREAD

**Issue by scoutrul** [nuxt/components#98] opened 2020-10-18 19:53 UTC
Is there any way to help IDEA (WebStorm for my case) to handle with component definations?

**Comment by Atinux** [comment] 2020-11-03 10:28
Duplicate of #51

**Closed** 2021-01-08 23:04 UTC

**Comment by JasonLandbridge** [comment] 2022-03-13 12:34
For those looking for a solution: [Nuxt-storm](https://github.com/fumeapp/nuxt-storm)
